module.exports = {
            darkMode: "class",
            theme: {
                extend: {
                    colors: {
                        "secondary-container": "#d4d4d4",
                        "surface-container-highest": "#e2e2e2",
                        "on-secondary-fixed-variant": "#3b3b3b",
                        "on-primary": "#e2e2e2",
                        "inverse-primary": "#c6c6c6",
                        "surface-tint": "#5e5e5e",
                        "surface-container": "#eeeeee",
                        "on-secondary-container": "#1b1b1b",
                        "on-error": "#ffffff",
                        "inverse-on-surface": "#f1f1f1",
                        "surface-bright": "#f9f9f9",
                        "on-primary-container": "#ffffff",
                        "tertiary": "#3b3b3b",
                        "surface-variant": "#e2e2e2",
                        "outline": "#777777",
                        "on-surface-variant": "#474747",
                        "on-secondary": "#ffffff",
                        "surface-container-high": "#e8e8e8",
                        "on-tertiary-container": "#ffffff",
                        "on-primary-fixed-variant": "#e2e2e2",
                        "surface-dim": "#dadada",
                        "tertiary-container": "#747474",
                        "on-tertiary-fixed": "#ffffff",
                        "surface-container-low": "#f3f3f3",
                        "on-secondary-fixed": "#1b1b1b",
                        "on-primary-fixed": "#ffffff",
                        "tertiary-fixed": "#5e5e5e",
                        "on-tertiary-fixed-variant": "#e2e2e2",
                        "secondary-fixed-dim": "#ababab",
                        "primary-fixed": "#5e5e5e",
                        "primary": "#000000",
                        "secondary": "#5e5e5e",
                        "error-container": "#ffdad6",
                        "secondary-fixed": "#c6c6c6",
                        "on-background": "#1b1b1b",
                        "inverse-surface": "#303030",
                        "on-tertiary": "#e2e2e2",
                        "tertiary-fixed-dim": "#474747",
                        "on-surface": "#1b1b1b",
                        "background": "#f9f9f9",
                        "surface-container-lowest": "#ffffff",
                        "surface": "#f9f9f9",
                        "primary-fixed-dim": "#474747",
                        "outline-variant": "#c6c6c6",
                        "on-error-container": "#410002",
                        "primary-container": "#3b3b3b",
                        "error": "#ba1a1a"
                    },
                    fontFamily: {
                        "headline": ["Space Grotesk"],
                        "body": ["Inter"],
                        "label": ["Inter"]
                    },
                    borderRadius: {"DEFAULT": "0px", "lg": "0px", "xl": "0px", "full": "9999px"},
                },
            },
        };