"""Generate the static portfolio index and browser data from the imported content."""
import json, html, pathlib, re
root=pathlib.Path(__file__).resolve().parents[1]
projects=json.loads((root/'content/portfolio.json').read_text())
esc=html.escape
cards=[]
for i,p in enumerate(projects,1):
 cover=p['cover'];label=p['client'] or p['category']
 count=len(p['images'])+sum(len(c.get('images',[])) for c in p.get('campaigns',[]))
 films=len(p['films'])+sum(len(c.get('films',[])) for c in p.get('campaigns',[]))
 media=' + '.join(([f'{count:02d} images'] if count else [])+([f'{films:02d} film'+('s' if films!=1 else '')] if films else []))
 action='Watch film' if films and not count else 'View project'
 cards.append(f'''        <a class="project" href="#project/{p['key']}" data-project="{p['key']}" aria-label="View {esc(p['title'])}, {esc(media)}"><div class="project-image"><img src="{cover['src']}" width="{cover['width']}" height="{cover['height']}" alt="{esc(p['title'])} — {esc(label)}" loading="lazy" decoding="async"><span class="project-open">{action} ↗</span></div><div class="project-caption"><div><h3>{esc(p['title'])}</h3><span>{esc(label)}</span></div><span class="project-type">{esc(media)} <span aria-hidden="true">↗</span></span></div></a>''')
index=root/'dist/index.html';s=index.read_text()
start=s.index('    <section id="work"');end=s.index('    <section class="about-section',start)
s=s[:start]+f'''    <section id="work" class="work-section section-pad" aria-labelledby="work-title">
      <div class="work-heading"><h2 id="work-title">SELECTED WORK<span> / {len(projects)}</span></h2><span class="eyebrow">Photography &amp; direction</span></div>
      <div class="project-grid">
'''+ '\n'.join(cards)+'''
      </div>
    </section>
'''+s[end:]
if 'portfolio-data.js' not in s:s=s.replace('  <script src="app.js"','  <script src="portfolio-data.js" defer></script>\n  <script src="app.js"')
index.write_text(s)
# Do not ship Wix metadata fields or raw CMS content that the interface doesn't use.
public={p['key']:{k:v for k,v in p.items() if k in ('title','client','category','year','location','description','cover','images','films','campaigns','credits')} for p in projects}
(root/'dist/portfolio-data.js').write_text('/* Generated by scripts/build-portfolio.py. Edit content/portfolio.json. */\nconst projects = '+json.dumps(public,ensure_ascii=False,separators=(',',':'))+';\n')
print(f'Generated {len(projects)} portfolio entries.')
