"""Generate the portfolio index, browser data, one crawlable page per project, and the sitemap from the imported content."""
import json, html, pathlib, re, datetime
root=pathlib.Path(__file__).resolve().parents[1]
projects=json.loads((root/'content/portfolio.json').read_text())
esc=html.escape
site='https://www.petersanjur.com'
# Projects imported from Wix keep their old /portfolio/<slug> address so existing search results still land.
def slug(p):
 m=re.search(r'/portfolio/([^/?#]+)',p.get('source') or '')
 return m.group(1) if m else p['key']
for p in projects:p['slug']=slug(p)
def media_counts(p):
 count=len(p['images'])+sum(len(c.get('images',[])) for c in p.get('campaigns',[]))
 films=len(p['films'])+sum(len(c.get('films',[])) for c in p.get('campaigns',[]))
 return count,films
cards=[]
for i,p in enumerate(projects,1):
 cover=p['cover'];label=p['client'] or p['category']
 count,films=media_counts(p)
 media=' + '.join(([f'{count:02d} images'] if count else [])+([f'{films:02d} film'+('s' if films!=1 else '')] if films else []))
 action='Watch film' if films and not count else 'View project'
 cards.append(f'''        <a class="project" href="portfolio/{p['slug']}/" data-project="{p['key']}" aria-label="View {esc(p['title'])}, {esc(media)}"><div class="project-image"><img src="{cover['src']}" width="{cover['width']}" height="{cover['height']}" alt="{esc(p['title'])} — {esc(label)}" loading="lazy" decoding="async"><span class="project-open">{action} ↗︎</span></div><div class="project-caption"><div><h3>{esc(p['title'])}</h3><span>{esc(label)}</span></div><span class="project-type">{esc(media)} <span aria-hidden="true">↗︎</span></span></div></a>''')
index=root/'dist/index.html';s=index.read_text()
start=s.index('    <section id="work"');end=s.index('    <section class="about-section',start)
s=s[:start]+f'''    <section id="work" class="work-section section-pad" aria-labelledby="work-title">
      <div class="work-heading"><h2 id="work-title">SELECTED WORK<span> / {len(projects)}</span></h2><span class="eyebrow">Photography &amp; direction</span></div>
      <div class="project-grid">
'''+ '\n'.join(cards)+'''
      </div>
    </section>
'''+s[end:]
if 'portfolio-data.js' not in s:s=s.replace('  <script src="app.js"','  <script src="portfolio-data.js" defer></script>\n  <script src="app.js"')
index.write_text(s)
# Do not ship Wix metadata fields or raw CMS content that the interface doesn't use.
public={p['key']:{k:v for k,v in p.items() if k in ('title','slug','client','client_url','press','category','year','location','description','cover','images','films','campaigns','credits')} for p in projects}
(root/'dist/portfolio-data.js').write_text('/* Generated by scripts/build-portfolio.py. Edit content/portfolio.json. */\nconst projects = '+json.dumps(public,ensure_ascii=False,separators=(',',':'))+';\n')

# Project pages mirror the homepage's project view (app.js renderProject) as plain HTML.
up='../../'
def render_images(images,title):
 out=[];paired=False
 for i,image in enumerate(images):
  landscape=image['width']>image['height'];following=images[i+1] if i+1<len(images) else None
  layout='gallery-landscape' if landscape else ''
  if not landscape:
   if paired:paired=False
   elif following and following['width']<=following['height']:paired=True
   else:layout='gallery-solo'
  out.append(f'<figure class="gallery-frame {layout}"><img src="{up}{esc(image["src"])}" width="{image["width"]}" height="{image["height"]}" alt="{esc(title)} — photograph {i+1} of {len(images)}, by Peter Sanjur" loading="{"eager" if i<2 else "lazy"}" decoding="async"><figcaption>{i+1:02d} / {len(images):02d}</figcaption></figure>')
 return ''.join(out)
def render_films(films,title,poster):
 return ''.join(f'<figure class="story-film {"film-portrait" if (f.get("width") or 1920)<(f.get("height") or 1080) else ""}"><div class="film-player"><video controls playsinline preload="none" poster="{up}{esc(f.get("poster") or poster)}" width="{f.get("width") or 1920}" height="{f.get("height") or 1080}" src="{up}{esc(f["src"])}"></video></div><figcaption>{esc(f.get("title") or title)}</figcaption></figure>' for f in films)
def render_campaign(p,i,c):
 films=c.get('films',[]);poster=p['cover']['src']
 tall=lambda f:(f.get('width') or 1920)<(f.get('height') or 1080)
 # Wide and tall films sit in separate rows, as in app.js.
 if len(films)==1:film_html=f'<div class="campaign-films single-film">{render_films(films,c["title"],poster)}</div>'
 else:
  groups=(('',[f for f in films if not tall(f)]),(' portrait-films',[f for f in films if tall(f)]))
  film_html=''.join(f'<div class="campaign-films film-group{extra}">{render_films(group,c["title"],poster)}</div>' for extra,group in groups if group)
 images=render_images(c.get('images',[]),f'{p["title"]} — {c["title"]}')
 description=f'<p>{esc(c["description"])}</p>' if c.get('description') else ''
 gallery=f'<div class="story-gallery">{images}</div>' if images else ''
 return f'<section class="campaign-section" id="campaign-{i}" aria-labelledby="campaign-title-{i}"><div class="campaign-heading"><span class="eyebrow">{i+1:02d} / {esc(p["client"])}</span><h2 id="campaign-title-{i}">{esc(c["title"])}</h2>{description}</div>{film_html}{gallery}</section>'
def summary(p):
 text=' '.join(p['description'].split())
 if not text:return f'{p["title"]}{" — "+p["client"] if p["client"] else ""}: {p["category"].lower() if p["category"] else "photography"} by Peter Sanjur, a Dallas photographer and director.'
 return text if len(text)<=158 else text[:155].rsplit(' ',1)[0]+'…'
pages=[]
for n,p in enumerate(projects):
 following=projects[(n+1)%len(projects)]
 sections=p.get('campaigns',[])
 count,films=media_counts(p)
 media=' + '.join(x for x in (f'{count} photographs' if count else '',f'{films} film{"" if films==1 else "s"}' if films else '') if x)
 paragraphs=''.join(f'<p>{esc(t).replace(chr(10),"<br>")}</p>' for t in re.split(r'\n\s*\n',p['description']) if t.strip())
 credits=''.join(f'<div><dt>{esc(c["role"])}</dt><dd>{esc(c["name"])}</dd></div>' for c in p.get('credits',[]))
 # Press features sit with the credits, as quiet links.
 credits+=''.join(f'<div><dt>Featured in</dt><dd><a class="quiet-link" href="{esc(f["url"])}" target="_blank" rel="noopener">{esc(f["name"])}</a></dd></div>' for f in p.get('press',[]))
 nav=f'<nav class="campaign-nav" aria-label="{esc(p["title"])} campaigns">'+''.join(f'<a href="#campaign-{i}">{esc(c["title"])} <span aria-hidden="true">↓</span></a>' for i,c in enumerate(sections))+'</nav>' if sections else ''
 gallery=render_images(p['images'],p['title'])
 url=f'{site}/portfolio/{p["slug"]}/'
 # The client's name links to their site when we have it.
 client=f'<a class="quiet-link" href="{esc(p["client_url"])}" target="_blank" rel="noopener">{esc(p["client"])}</a>' if p.get('client_url') and p['client'] else esc(p['client'] or '')
 label=' / '.join(x for x in (client,esc(p['category'] or '')) if x)
 title=f'{p["title"]}{" — "+p["client"] if p["client"] and p["client"]!=p["title"] else ""} | Peter Sanjur'
 data={'@context':'https://schema.org','@type':'CreativeWork','name':p['title'],'url':url,'image':f'{site}/{p["cover"]["src"]}','description':summary(p),'creator':{'@type':'Person','name':'Peter Sanjur','url':f'{site}/'}}
 if p.get('year'):data['dateCreated']=str(p['year'])
 if p['client'] and p['client']!=p['title']:data['sourceOrganization']={'@type':'Organization','name':p['client']}
 page=f'''<!doctype html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>{esc(title)}</title>
  <meta name="description" content="{esc(summary(p))}">
  <link rel="canonical" href="{url}">
  <meta name="theme-color" content="#f7f7f5">
  <meta property="og:type" content="article">
  <meta property="og:site_name" content="Peter Sanjur">
  <meta property="og:title" content="{esc(title)}">
  <meta property="og:description" content="{esc(summary(p))}">
  <meta property="og:url" content="{url}">
  <meta property="og:image" content="{site}/{esc(p["cover"]["src"])}">
  <meta name="twitter:card" content="summary_large_image">
  <link rel="icon" type="image/svg+xml" href="data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 64 64'%3E%3Crect width='64' height='64' fill='%23ffffff'/%3E%3Ctext x='8' y='45' font-family='Arial' font-size='38' font-weight='700' fill='%23080808'%3EPS%3C/text%3E%3C/svg%3E">
  <link rel="stylesheet" href="{up}styles.css">
  <link rel="stylesheet" href="{up}palette.css">
  <script type="application/ld+json">{json.dumps(data,ensure_ascii=False)}</script>
  <!-- Visitor stats: peterasanjur.goatcounter.com -->
  <script data-goatcounter="https://peterasanjur.goatcounter.com/count" async src="https://gc.zgo.at/count.js"></script>
</head>
<body class="project-page">
  <a class="skip-link" href="#main">Skip to content</a>
  <header class="dialog-top"><a class="wordmark" href="{up}index.html" aria-label="Peter Sanjur home">PS</a><span class="eyebrow">Selected work / Peter Sanjur</span><a class="close-dialog" href="{up}index.html#work">All work <span aria-hidden="true">×</span></a></header>
  <main id="main"><article class="project-story"><div class="story-heading"><span class="eyebrow">{label}</span><h1>{esc(p["title"])}</h1><div class="story-meta"><span>{esc(" / ".join(str(x) for x in (p["location"],p["year"]) if x))}</span><span>{media}</span></div></div>{f'<div class="story-breakdown"><span class="eyebrow">About the project</span><div>{paragraphs}</div></div>' if paragraphs else ''}{f'<section class="story-credits" aria-label="Project credits"><span class="eyebrow">Credits</span><dl>{credits}</dl></section>' if credits else ''}{nav}{render_films(p["films"],p["title"],p["cover"]["src"])}{f'<div class="story-gallery" aria-label="{esc(p["title"])} photographs">{gallery}</div>' if gallery else ''}{''.join(render_campaign(p,i,c) for i,c in enumerate(sections))}<div class="story-end"><a class="text-link" href="{up}index.html#work">Back to all work ↗︎</a><a class="next-project" href="../{following["slug"]}/"><span class="eyebrow">Next project</span>{esc(following["title"])} ↗︎</a></div></article></main>
</body>
</html>
'''
 folder=root/'dist/portfolio'/p['slug'];folder.mkdir(parents=True,exist_ok=True)
 (folder/'index.html').write_text(page)
 pages.append(url)

# Sitemap: the homepage, the studio, and every project page.
today=datetime.date.today().isoformat()
urls=[f'{site}/',f'{site}/studio.html']+pages
(root/'dist/sitemap.xml').write_text('<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n'+''.join(f'  <url><loc>{u}</loc><lastmod>{today}</lastmod></url>\n' for u in urls)+'</urlset>\n')
print(f'Generated {len(projects)} portfolio entries, {len(pages)} project pages, and a sitemap of {len(urls)} URLs.')
